version: '3'

services:
    db:
        container_name: 'shortener_postgres'
        image: 'postgres:14'
        restart: always
        env_file:
            - ./.env
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'